/**
 * Evidence Package 校验
 *
 * 提供 EvidencePackage 的完整性校验、证据覆盖率计算、
 * 以及证据充分性检查。
 */

import type { EvidencePackage, FindingEvidence } from "./types.js";

// ============================================================================
// 校验结果
// ============================================================================

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

// ============================================================================
// 校验 Evidence Package 完整性
// ============================================================================

/**
 * 校验 Evidence Package 完整性
 *
 * 检查项：
 * 1. version 必须为 1
 * 2. sessionId 不能为空
 * 3. question 不能为空
 * 4. 至少有一个 query 且成功
 * 5. 所有 FindingEvidence 的 resultRefs/chartRefs/queryRefs 引用的 ID 必须存在
 * 6. 图表必须有关联的查询或结果
 * 7. findings 的 confidence 必须为 high/medium/low
 */
export function validateEvidencePackage(pkg: EvidencePackage): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // 1. version 必须为 1
  if (pkg.version !== 1) {
    errors.push(`Invalid version: expected 1, got ${pkg.version}`);
  }

  // 2. sessionId 不能为空
  if (!pkg.sessionId || pkg.sessionId.trim().length === 0) {
    errors.push("sessionId must not be empty");
  }

  // 3. question 不能为空
  if (!pkg.question || pkg.question.trim().length === 0) {
    errors.push("question must not be empty");
  }

  // 4. 至少有一个 query 且成功
  const successfulQueries = pkg.queries.filter((q) => q.success);
  if (pkg.queries.length === 0) {
    errors.push("No queries found in evidence package");
  } else if (successfulQueries.length === 0) {
    errors.push("No successful queries found in evidence package");
  }

  // 构建引用索引
  const existingQueryIds = new Set(pkg.queries.map((q) => q.id));
  const existingChartIds = new Set(pkg.charts.map((c) => c.id));

  // 5. 校验 FindingEvidence 的引用
  for (const finding of pkg.findings) {
    // resultRefs（QueryEvidence IDs）
    for (const ref of finding.resultRefs) {
      if (!existingQueryIds.has(ref)) {
        errors.push(`Finding "${finding.id}" references non-existent query: ${ref}`);
      }
    }

    // chartRefs
    for (const ref of finding.chartRefs) {
      if (!existingChartIds.has(ref)) {
        errors.push(`Finding "${finding.id}" references non-existent chart: ${ref}`);
      }
    }

    // queryRefs
    for (const ref of finding.queryRefs) {
      if (!existingQueryIds.has(ref)) {
        errors.push(`Finding "${finding.id}" references non-existent query: ${ref}`);
      }
    }

    // metricRefs
    const existingMetricIds = new Set(pkg.metrics.map((m) => m.id));
    for (const ref of finding.metricRefs) {
      if (!existingMetricIds.has(ref)) {
        errors.push(`Finding "${finding.id}" references non-existent metric: ${ref}`);
      }
    }
  }

  // 6. 图表必须有关联的查询或结果
  for (const chart of pkg.charts) {
    if (!chart.sourceQueryId && !chart.filePath && !chart.dataUrl) {
      warnings.push(`Chart "${chart.id}" has no associated query, file path, or data URL`);
    }
  }

  // 7. findings 的 confidence 必须为有效值
  const validConfidences = new Set<string>(["high", "medium", "low"]);
  for (const finding of pkg.findings) {
    if (!validConfidences.has(finding.confidence)) {
      errors.push(`Finding "${finding.id}" has invalid confidence: ${finding.confidence}`);
    }
  }

  // 额外警告检查
  if (pkg.findings.length === 0) {
    warnings.push("No findings in evidence package — findings will be generated by model (Task 3)");
  }

  if (pkg.dictionary.length === 0) {
    warnings.push("No dictionary snapshots — field semantics may not be validated");
  }

  if (pkg.metrics.length === 0) {
    warnings.push("No metric snapshots — calibers may not be defined");
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// ============================================================================
// 证据覆盖率
// ============================================================================

/**
 * 计算证据覆盖率
 *
 * coverage = 有有效证据引用的核心结论数 / 核心结论总数
 * hypothesis 不计入量化核心结论
 *
 * 有效证据引用 = 至少有一个 queryRef、chartRef、resultRef 或 metricRef
 *
 * 注意：当没有 core findings 时返回 0（而非 1.0），表示无证据覆盖。
 * 上层（如 report-quality-gate）应通过 findings.length > 0 条件跳过此场景。
 */
export function calculateEvidenceCoverage(pkg: EvidencePackage): number {
  const coreFindings = pkg.findings.filter(
    (f) => f.evidenceType !== "hypothesis"
  );

  if (coreFindings.length === 0) {
    // 没有 findings 时返回 0（无证据可覆盖）
    // 上层调用方需要自行决定如何处理（例如在质量门槛中跳过此检查）
    return 0;
  }

  const findingsWithEvidence = coreFindings.filter((f) => {
    const totalRefs =
      f.resultRefs.length +
      f.chartRefs.length +
      f.queryRefs.length +
      f.metricRefs.length;
    return totalRefs > 0;
  });

  return findingsWithEvidence.length / coreFindings.length;
}

// ============================================================================
// 证据充分性检查
// ============================================================================

/**
 * 检查分析是否有足够证据生成报告
 *
 * 返回缺失项列表，空数组表示可以生成。
 *
 * 检查项：
 * - 是否有至少一个成功的查询
 * - 是否有数据集信息
 * - 是否有足够的查询结果支撑分析（至少 1 个查询有结果）
 */
export function checkEvidenceSufficiency(pkg: EvidencePackage): string[] {
  const missing: string[] = [];

  // 是否有至少一个成功的查询
  const successfulQueries = pkg.queries.filter((q) => q.success);
  if (successfulQueries.length === 0) {
    missing.push("No successful queries available as evidence");
  }

  // 是否有数据集信息
  if (pkg.scope.datasets.length === 0) {
    missing.push("No dataset information identified from queries");
  }

  // 是否有至少 1 个查询有实质结果
  const queriesWithResults = successfulQueries.filter(
    (q) => q.rowCount > 0 || (q.resultSummary && q.resultSummary.trim().length > 0)
  );
  if (queriesWithResults.length === 0) {
    missing.push("No queries returned substantive results");
  }

  return missing;
}
