/**
 * Task 2 — HTML 报告模板（Catppuccin Mocha 暗色主题）
 *
 * 纯字符串模板，内联 <style>，不依赖任何前端框架。
 * v0.5 新增：SQL 高亮卡片、字典面板、meta summary、索引链接
 */

import type { TranscriptMessage, ToolCallInfo } from "./session-transcript.js";
import { maskPII } from "../pii-guard.js";
import { highlightSql, getFirstLines, exceedsLines } from "./sql-highlight.js";
import { DICTIONARY_CSS } from "./dictionary-panel.js";

/**
 * 生成完整的 HTML 报告字符串
 */
export function buildHtmlFrame(params: {
  title: string;
  generatedAt: string;
  messagesHtml: string;
  chartsHtml: string;
  tocHtml: string;
  dictPanelHtml?: string;
  metaSummary?: string;
  metaDatasets?: string;
  indexLinkHtml?: string;
}): string {
  const { title, generatedAt, messagesHtml, chartsHtml, tocHtml, dictPanelHtml, metaSummary, metaDatasets, indexLinkHtml } = params;

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
${metaSummary ? `<meta name="summary" content="${escapeHtml(metaSummary)}">` : ""}
${metaDatasets ? `<meta name="datasets" content="${escapeHtml(metaDatasets)}">` : ""}
<title>${escapeHtml(title)}</title>
<style>
${STYLES}
${DICTIONARY_CSS}
${SQL_HIGHLIGHT_CSS}
</style>
</head>
<body>
<div class="container">
  <header class="header">
    <h1 class="title">${escapeHtml(title)}</h1>
    <p class="meta">Generated: ${escapeHtml(generatedAt)}</p>
    ${indexLinkHtml ?? ""}
  </header>

  ${dictPanelHtml ?? ""}

  ${tocHtml ? `<nav class="toc">${tocHtml}</nav>` : ""}

  <section class="messages">
    ${messagesHtml}
  </section>

  ${chartsHtml ? `<section class="charts-section">
    <h2 class="section-title">Charts</h2>
    ${chartsHtml}
  </section>` : ""}

  <footer class="footer">
    <p>Generated by Pi Data Agent v0.5 &middot; Offline self-contained report</p>
  </footer>
</div>

<script>
${SCRIPT}
</script>
</body>
</html>`;
}

// ============================================================================
// 消息气泡渲染
// ============================================================================

/**
 * 将 transcript 消息数组渲染为 HTML 消息流
 */
export function renderMessages(messages: TranscriptMessage[]): string {
  return messages
    .filter((m) => {
      if (m.role === "toolResult") return false;
      if (m.role === "branchSummary") return false;
      if (m.role === "compactionSummary") return false;
      if (m.role === "unknown") return false;
      if (m.role === "bashExecution") return false;
      return true;
    })
    .map((msg, index) => {
      const anchor = `msg-${index}`;
      const time = formatTime(msg.timestamp);

      switch (msg.role) {
        case "user":
          return renderBubble({
            anchor,
            cssClass: "bubble-user",
            label: "You",
            time,
            content: maskPII(msg.content).masked,
          });

        case "assistant":
          return renderAssistantBubble(msg, anchor, time, index);

        case "custom":
          return renderBubble({
            anchor,
            cssClass: "bubble-system",
            label: "System",
            time,
            content: msg.content,
          });

        default:
          return "";
      }
    })
    .join("\n");
}

/**
 * 渲染助手消息（含工具调用卡片）
 */
function renderAssistantBubble(
  msg: TranscriptMessage,
  anchor: string,
  time: string,
  index: number
): string {
  const parts: string[] = [];

  if (msg.content.trim()) {
    parts.push(renderBubble({
      anchor,
      cssClass: "bubble-assistant",
      label: "Assistant",
      time,
      content: msg.content,
    }));
  }

  if (msg.toolCalls && msg.toolCalls.length > 0) {
    for (const tc of msg.toolCalls) {
      parts.push(renderToolCallCard(tc, index));
    }
  }

  return parts.join("\n");
}

/**
 * 渲染工具调用摘要卡片
 */
function renderToolCallCard(tc: ToolCallInfo, msgIndex: number): string {
  const errorClass = tc.isError ? "tool-card-error" : "";
  const statusBadge = tc.isError
    ? '<span class="badge badge-error">ERROR</span>'
    : '<span class="badge badge-success">OK</span>';

  // 数据来源标签（仅 query_data / visualize）
  const dataSource = (tc.name === "query_data" || tc.name === "visualize")
    ? extractFirstTableName(tc.argsSummary)
    : null;
  const dataSourceHtml = dataSource
    ? `<span class="tool-data-source" title="数据来源">${escapeHtml(dataSource)}</span>`
    : "";

  // query_data 使用 SQL 高亮卡片
  const argsDisplay = tc.name === "query_data"
    ? renderSqlCard(tc.argsSummary)
    : `<pre class="args-raw">${escapeHtml(tc.argsSummary)}</pre>`;

  return `
<div class="tool-card ${errorClass}">
  <div class="tool-card-header">
    <span class="tool-name">${escapeHtml(tc.name)}</span>
    ${dataSourceHtml}
    ${statusBadge}
  </div>
  ${argsDisplay ? `<div class="tool-args">${argsDisplay}</div>` : ""}
  ${tc.resultSummary ? `<div class="tool-result">${escapeHtml(tc.resultSummary)}</div>` : ""}
</div>`;
}

/**
 * 从参数摘要中提取第一个表名（用于数据来源标签）
 */
function extractFirstTableName(argsSummary: string): string | null {
  try {
    const args = JSON.parse(argsSummary);
    const sql = args.sql;
    if (typeof sql !== "string") return null;
    const cleaned = sql
      .replace(/'[^']*'/g, "''")
      .replace(/--[^\n]*/g, "")
      .replace(/\/\*[\s\S]*?\*\//g, "");
    const m = cleaned.match(/\bFROM\s+([a-zA-Z_][a-zA-Z0-9_]*)/i);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

/**
 * 渲染 SQL 卡片 — 高亮 + 默认折叠前 3 行
 *
 * 使用 <details> 无需 JS，纯 HTML/CSS 实现展开/折叠。
 */
function renderSqlCard(argsSummary: string): string {
  let sql = "";
  try {
    const args = JSON.parse(argsSummary);
    sql = args.sql ?? "";
  } catch {
    // JSON 解析失败，尝试从摘要中提取
    const match = argsSummary.match(/"sql"\s*:\s*"([^"]*)"/);
    sql = match ? match[1] : argsSummary;
  }

  if (!sql) {
    return `<pre class="args-raw">${escapeHtml(argsSummary)}</pre>`;
  }

  const highlighted = highlightSql(sql);
  const first3 = getFirstLines(sql, 3);
  const highlightedFirst3 = highlightSql(first3);
  const needExpand = exceedsLines(sql, 3);

  const copyBtn = `<button class="sql-copy-btn" data-sql="${escapeHtml(sql)}" title="复制 SQL">复制</button>`;

  if (!needExpand) {
    return `<div class="sql-card">
  <div class="sql-card-header">
    <span class="sql-card-label">SQL</span>
    ${copyBtn}
  </div>
  <pre class="sql-card-body"><code>${highlighted}</code></pre>
</div>`;
  }

  // 超过 3 行：默认折叠，用 <details>
  return `<div class="sql-card">
  <div class="sql-card-header">
    <span class="sql-card-label">SQL</span>
    ${copyBtn}
  </div>
  <details class="sql-details">
    <summary class="sql-summary">
      <pre class="sql-preview"><code>${highlightedFirst3}</code></pre>
      <span class="sql-expand-hint">▼ 展开完整语句</span>
    </summary>
    <pre class="sql-card-body sql-full"><code>${highlighted}</code></pre>
  </details>
</div>`;
}

/**
 * 渲染单条消息气泡
 */
function renderBubble(params: {
  anchor: string;
  cssClass: string;
  label: string;
  time: string;
  content: string;
}): string {
  const { anchor, cssClass, label, time, content } = params;
  const htmlContent = formatContent(content);

  return `
<div class="bubble ${cssClass}" id="${anchor}">
  <div class="bubble-header">
    <span class="bubble-label">${label}</span>
    <span class="bubble-time">${time}</span>
  </div>
  <div class="bubble-body">${htmlContent}</div>
</div>`;
}

/**
 * 格式化消息内容（简单的 Markdown 渲染）
 */
function formatContent(text: string): string {
  if (!text) return "";

  let html = escapeHtml(text);

  // 代码块
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_m, _lang, code) => {
    return `<pre class="code-block"><code>${code.trim()}</code></pre>`;
  });

  // 行内代码
  html = html.replace(/`([^`]+)`/g, "<code class=\"inline-code\">$1</code>");

  // 粗体
  html = html.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");

  // 换行
  html = html.replace(/\n/g, "<br>");

  return html;
}

/**
 * 渲染图表区块
 */
export function renderChartsSection(inlineResults: Array<{
  inlined: boolean;
  originalPath: string;
  dataUri?: string;
  skipReason?: string;
}>): string {
  if (inlineResults.length === 0) return "";

  const items = inlineResults.map((r, i) => {
    if (r.inlined && r.dataUri) {
      return `<div class="chart-item">
  <img src="${r.dataUri}" alt="Chart ${i + 1}" class="chart-img" loading="lazy" />
  <p class="chart-path">${escapeHtml(r.originalPath)}</p>
</div>`;
    }
    return `<div class="chart-item chart-skipped">
  <p class="chart-skip-reason">${escapeHtml(r.skipReason ?? "Unknown")}</p>
  <p class="chart-path">${escapeHtml(r.originalPath)}</p>
</div>`;
  });

  return items.join("\n");
}

/**
 * 生成锚点导航目录
 */
export function renderToc(messages: TranscriptMessage[]): string {
  const items: string[] = [];
  let msgIndex = 0;

  for (const msg of messages) {
    if (msg.role === "toolResult" || msg.role === "branchSummary" ||
        msg.role === "compactionSummary" || msg.role === "unknown" ||
        msg.role === "bashExecution") continue;

    const anchor = `msg-${msgIndex}`;
    const time = formatTime(msg.timestamp);
    const preview = maskPII(msg.content.slice(0, 60).replace(/\n/g, " ")).masked;

    let label = "";
    switch (msg.role) {
      case "user":
        label = "You";
        break;
      case "assistant":
        label = "Assistant";
        break;
      case "custom":
        label = "System";
        break;
    }

    items.push(`<a href="#${anchor}" class="toc-item">
  <span class="toc-label">${label}</span>
  <span class="toc-preview">${escapeHtml(preview)}</span>
  <span class="toc-time">${time}</span>
</a>`);

    msgIndex++;
  }

  if (items.length === 0) return "";

  return `<h2 class="toc-title">Navigation</h2>\n${items.join("\n")}`;
}

// ============================================================================
// 工具函数
// ============================================================================

/** HTML 转义 */
function escapeHtml(str: string): string {
  if (!str) return "";
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** 格式化 ISO 时间戳为可读格式 */
function formatTime(ts: string): string {
  try {
    const d = new Date(ts);
    return d.toLocaleString("zh-CN", {
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  } catch {
    return ts;
  }
}

// ============================================================================
// CSS 样式
// ============================================================================

const STYLES = `
/* === 深浅色主题切换 === */
:root {
  --bg: #1e1e2e;
  --bg-secondary: #181825;
  --bg-surface: #313244;
  --fg: #cdd6f4;
  --fg-muted: #a6adc8;
  --accent: #a6e3a1;
  --accent-secondary: #89b4fa;
  --red: #f38ba8;
  --yellow: #f9e2af;
  --border: #45475a;
  --user-bg: #313244;
  --assistant-bg: #1e1e2e;
  --tool-bg: #181825;
  --code-bg: #11111b;
  --radius: 8px;
  --max-width: 900px;
}

@media (prefers-color-scheme: light) {
  :root {
    --bg: #eff1f5;
    --bg-secondary: #e6e9ef;
    --bg-surface: #ccd0da;
    --fg: #4c4f69;
    --fg-muted: #6c6f85;
    --accent: #40a02b;
    --accent-secondary: #1e66f5;
    --red: #d20f39;
    --yellow: #df8e1d;
    --border: #bcc0cc;
    --user-bg: #ccd0da;
    --assistant-bg: #eff1f5;
    --tool-bg: #e6e9ef;
    --code-bg: #dce0e8;
  }
}

/* === 基础 === */
* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  background: var(--bg);
  color: var(--fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans SC", sans-serif;
  font-size: 14px;
  line-height: 1.6;
  padding: 20px;
}

.container {
  max-width: var(--max-width);
  margin: 0 auto;
}

/* === Header === */
.header {
  padding: 24px 0;
  border-bottom: 1px solid var(--border);
  margin-bottom: 24px;
}

.title {
  font-size: 22px;
  font-weight: 700;
  color: var(--accent);
  margin-bottom: 4px;
}

.meta {
  color: var(--fg-muted);
  font-size: 12px;
}

.index-link {
  margin-top: 8px;
  font-size: 13px;
}

.index-link a {
  color: var(--accent-secondary);
  text-decoration: none;
}

.index-link a:hover {
  text-decoration: underline;
}

/* === TOC === */
.toc {
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 16px;
  margin-bottom: 24px;
}

.toc-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--accent-secondary);
  margin-bottom: 8px;
}

.toc-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 4px 8px;
  border-radius: 4px;
  text-decoration: none;
  color: var(--fg);
  font-size: 13px;
  transition: background 0.15s;
}

.toc-item:hover {
  background: var(--bg-surface);
}

.toc-label {
  font-weight: 600;
  min-width: 60px;
  color: var(--accent);
}

.toc-preview {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: var(--fg-muted);
}

.toc-time {
  font-size: 11px;
  color: var(--fg-muted);
  opacity: 0.7;
}

/* === Messages === */
.messages {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-bottom: 24px;
}

.bubble {
  border-radius: var(--radius);
  padding: 12px 16px;
  max-width: 100%;
}

.bubble-user {
  background: var(--user-bg);
  margin-left: 40px;
  border: 1px solid var(--border);
}

.bubble-assistant {
  background: var(--assistant-bg);
  margin-right: 40px;
  border: 1px solid var(--border);
}

.bubble-system {
  background: var(--bg-secondary);
  border: 1px dashed var(--border);
  font-size: 13px;
}

.bubble-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 6px;
}

.bubble-label {
  font-weight: 600;
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.bubble-user .bubble-label { color: var(--accent); }
.bubble-assistant .bubble-label { color: var(--accent-secondary); }
.bubble-system .bubble-label { color: var(--fg-muted); }

.bubble-time {
  font-size: 11px;
  color: var(--fg-muted);
  opacity: 0.6;
}

.bubble-body {
  color: var(--fg);
  word-wrap: break-word;
  overflow-wrap: break-word;
}

/* === Tool Cards === */
.tool-card {
  background: var(--tool-bg);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 10px 14px;
  margin-top: 8px;
  margin-left: 40px;
}

.tool-card-error {
  border-color: var(--red);
}

.tool-card-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 6px;
}

.tool-name {
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 12px;
  font-weight: 600;
  color: var(--accent-secondary);
}

.badge {
  font-size: 10px;
  font-weight: 700;
  padding: 1px 6px;
  border-radius: 3px;
  text-transform: uppercase;
}

.badge-success {
  background: rgba(166, 227, 161, 0.15);
  color: var(--accent);
}

.badge-error {
  background: rgba(243, 139, 168, 0.15);
  color: var(--red);
}

.tool-args {
  margin-bottom: 6px;
}

.args-raw {
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 11px;
  color: var(--fg-muted);
  white-space: pre-wrap;
  word-break: break-all;
  max-height: 80px;
  overflow: hidden;
}

.tool-result {
  font-size: 12px;
  color: var(--fg-muted);
  border-top: 1px solid var(--border);
  padding-top: 6px;
  margin-top: 4px;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 120px;
  overflow: hidden;
}

/* === Code === */
.code-block {
  background: var(--code-bg);
  border-radius: 4px;
  padding: 10px 14px;
  overflow-x: auto;
  margin: 6px 0;
}

.code-block code {
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 12px;
  color: var(--fg);
  white-space: pre-wrap;
}

.inline-code {
  background: var(--bg-surface);
  padding: 1px 4px;
  border-radius: 3px;
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 12px;
}

/* === Charts === */
.charts-section {
  margin-bottom: 24px;
}

.section-title {
  font-size: 16px;
  font-weight: 600;
  color: var(--accent);
  margin-bottom: 12px;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--border);
}

.chart-item {
  margin-bottom: 16px;
  text-align: center;
}

.chart-img {
  max-width: 100%;
  border-radius: var(--radius);
  border: 1px solid var(--border);
}

.chart-path {
  font-size: 11px;
  color: var(--fg-muted);
  margin-top: 4px;
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  word-break: break-all;
}

.chart-skipped {
  padding: 12px;
  border: 1px dashed var(--border);
  border-radius: var(--radius);
}

.chart-skip-reason {
  color: var(--yellow);
  font-size: 13px;
  margin-bottom: 4px;
}

/* === Footer === */
.footer {
  padding-top: 16px;
  border-top: 1px solid var(--border);
  text-align: center;
  color: var(--fg-muted);
  font-size: 12px;
  opacity: 0.6;
}
`;

// ============================================================================
// SQL 高亮 CSS
// ============================================================================

const SQL_HIGHLIGHT_CSS = `
/* === SQL 卡片 === */
.sql-card {
  background: var(--code-bg);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  overflow: hidden;
}

.sql-card-header {
  display: flex;
  align-items: center;
  padding: 4px 10px;
  background: var(--bg-surface);
  border-bottom: 1px solid var(--border);
}

.sql-card-label {
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 10px;
  font-weight: 700;
  color: var(--accent-secondary);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.sql-card-body {
  padding: 8px 12px;
  margin: 0;
  overflow-x: auto;
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 12px;
  line-height: 1.5;
}

.sql-card-body code {
  font-family: inherit;
  font-size: inherit;
  color: var(--fg);
  white-space: pre-wrap;
  word-break: break-all;
}

/* SQL 折叠 */
.sql-details {
  border: none;
}

.sql-summary {
  list-style: none;
  cursor: pointer;
  padding: 0;
  position: relative;
}

.sql-summary::-webkit-details-marker {
  display: none;
}

.sql-preview {
  padding: 8px 12px;
  margin: 0;
  overflow-x: auto;
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 12px;
  line-height: 1.5;
}

.sql-preview code {
  font-family: inherit;
  font-size: inherit;
  color: var(--fg);
}

.sql-expand-hint {
  display: block;
  text-align: center;
  font-size: 11px;
  color: var(--accent-secondary);
  padding: 2px 0 6px;
  opacity: 0.7;
}

.sql-details[open] .sql-expand-hint {
  display: none;
}

.sql-full {
  border-top: 1px solid var(--border);
}

/* === SQL 复制按钮 === */
.sql-copy-btn {
  margin-left: auto;
  padding: 1px 8px;
  border: 1px solid var(--border);
  border-radius: 4px;
  background: var(--bg-secondary);
  color: var(--fg-muted);
  font-size: 11px;
  cursor: pointer;
  transition: all 0.15s;
}

.sql-copy-btn:hover {
  background: var(--bg-surface);
  color: var(--accent);
  border-color: var(--accent);
}

/* === 数据来源标签 === */
.tool-data-source {
  font-family: "SF Mono", "Fira Code", "JetBrains Mono", monospace;
  font-size: 10px;
  color: var(--fg-muted);
  background: var(--bg-surface);
  padding: 1px 6px;
  border-radius: 3px;
  border: 1px solid var(--border);
}

/* === SQL Token 颜色 === */
.sql-kw  { color: #cba6f7; font-weight: 600; }  /* 紫色关键字 */
.sql-str { color: #a6e3a1; }                   /* 绿色字符串 */
.sql-num { color: #fab387; }                   /* 橙色数字 */
.sql-cmt { color: #6c7086; font-style: italic; } /* 灰色注释 */
.sql-op  { color: #89dceb; }                   /* 青色操作符 */
.sql-id  { color: #f9e2af; }                   /* 黄色标识符 */
`;

// ============================================================================
// 客户端脚本
// ============================================================================

const SCRIPT = `
// 深浅色主题手动切换
(function() {
  const toggle = document.createElement('button');
  toggle.textContent = '\\u263E';
  toggle.title = 'Toggle theme';
  toggle.style.cssText = 'position:fixed;bottom:20px;right:20px;z-index:999;' +
    'width:36px;height:36px;border-radius:50%;border:1px solid var(--border);' +
    'background:var(--bg-secondary);color:var(--fg);cursor:pointer;font-size:16px;' +
    'display:flex;align-items:center;justify-content:center;transition:all 0.2s;';
  document.body.appendChild(toggle);

  let dark = true;
  toggle.addEventListener('click', function() {
    dark = !dark;
    document.documentElement.style.setProperty('--bg', dark ? '#1e1e2e' : '#eff1f5');
    document.documentElement.style.setProperty('--bg-secondary', dark ? '#181825' : '#e6e9ef');
    document.documentElement.style.setProperty('--bg-surface', dark ? '#313244' : '#ccd0da');
    document.documentElement.style.setProperty('--fg', dark ? '#cdd6f4' : '#4c4f69');
    document.documentElement.style.setProperty('--fg-muted', dark ? '#a6adc8' : '#6c6f85');
    document.documentElement.style.setProperty('--accent', dark ? '#a6e3a1' : '#40a02b');
    document.documentElement.style.setProperty('--accent-secondary', dark ? '#89b4fa' : '#1e66f5');
    document.documentElement.style.setProperty('--red', dark ? '#f38ba8' : '#d20f39');
    document.documentElement.style.setProperty('--yellow', dark ? '#f9e2af' : '#df8e1d');
    document.documentElement.style.setProperty('--border', dark ? '#45475a' : '#bcc0cc');
    document.documentElement.style.setProperty('--user-bg', dark ? '#313244' : '#ccd0da');
    document.documentElement.style.setProperty('--assistant-bg', dark ? '#1e1e2e' : '#eff1f5');
    document.documentElement.style.setProperty('--tool-bg', dark ? '#181825' : '#e6e9ef');
    document.documentElement.style.setProperty('--code-bg', dark ? '#11111b' : '#dce0e8');
    toggle.textContent = dark ? '\\u263E' : '\\u2600';
  });
})();

// SQL 复制按钮
(function() {
  document.querySelectorAll('.sql-copy-btn').forEach(function(btn) {
    btn.addEventListener('click', function(e) {
      e.preventDefault();
      var sql = this.getAttribute('data-sql');
      if (!sql) return;
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(sql).then(function() {
          btn.textContent = '已复制';
          setTimeout(function() { btn.textContent = '复制'; }, 2000);
        }).catch(function() {
          fallbackSelect(btn);
        });
      } else {
        fallbackSelect(btn);
      }
    });
  });

  function fallbackSelect(btn) {
    var card = btn.closest('.sql-card');
    if (!card) return;
    var pre = card.querySelector('pre.sql-card-body, pre.sql-full');
    if (!pre) return;
    var range = document.createRange();
    range.selectNodeContents(pre);
    var sel = window.getSelection();
    sel.removeAllRanges();
    sel.addRange(range);
    btn.textContent = '已选中';
    setTimeout(function() { btn.textContent = '复制'; }, 2000);
  }
})();
`;
